### ISSUE TITLE
cannot read properties of undefined.. nach Leckage aenderungen an der App

### ISSUE THREAD

**Issue by Ilovegym66** [eifel-tech/ioBroker.syrconnect#194]
Ich musste mit der App ein Profil loeschen, und habe an der Anwesend-Einstellung ein paar Aenderungen gemacht, jetzt startet der Adapter mit dem Fehler:

syrconnect.0 | 2024-11-08 10:20:51.633 | error | TypeError: Cannot read properties of undefined (reading 'type')
-- | -- | -- | --
syrconnect.0 | 2024-11-08 10:20:51.607 | debug | /WebServices/SyrConnectLimexWebService.asmx/GetAllCommands: <?xml version="1.0" encoding="utf-8"?> <sc version="1.0"> <d> <c n="getSRN" v="232657019" /> <c n="getVER" v="1.9" /> <c n="getFIR" v="TLPL" /> <c n="getTYP" v="80" /> <c n="getCNA" v="LEXplus10SL" /> <c n="get71" v="0" /> <c n="getAB" v="1" /> <c n="getALA" v="0" /> <c n="getAVO" v="5160mL" /> <c n="getBSA" v="0" /> <c n="getBUZ" v="" /> <c n="getCDE" v="010SCA19DF0917.01.024.1.1.0010" /> <c n="getCDF" v="125,107,190,159,81,0,0" /> <c n="getCEL" v="178" /> <c n="getCES" v="1" /> <c n="getCND" v="258" /> <c n="getCNO" v="" /> <c n="getCNS" v="1" /> <c n="getCOF" v="18074" /> <c n="getCS1" v="91" /> <c n="getCYN" v="0" /> <c n="getCYT" v="00:00" /> <c n="getDAT" v="1731061242" /> <c n="getDBD" v="10" /> <c n="getDBT" v="15" /> <c n="getDCM" v="3" /> <c n="getDEN" v="1" /> <c n="getDGW" v="0.0.0.0" /> <c n="getDMA" v="1" /> <c n="getDOM" v="60" /> <c n="getDPL" v="10" /> <c n="getDRP" v="1" /> <c n="getDST" v="180" /> <c n="getDTC" v="3" /> <c n="getDWF" v="200" /> <c n="getFCO" v="0" /> <c n="getFLO" v="7" /> <c n="getFSL" v="[]" /> <c n="getIDS" v="" /> <c n="getINR" v="0" /> <c n="getIPA" v="0.0.0.0" /> <c n="getIWH" v="22" /> <c n="getLAN" v="1" /> <c n="getLAR" v="1730994259" /> <c n="getLDF" v="149,158,107,197,141,146,361" /> <c n="getLWT" v="90" /> <c n="getMAC" v="0c:73:eb:52:55:07" /> <c n="getMAN" v="Syr" /> <c n="getMTF" v="0,0,0,0,0,0,0,5777,5693,5294,1310,0" /> <c n="getNOR" v="30" /> <c n="getNOT" v="" /> <c n="getNPS" v="0" /> <c n="getOHF" v="0,0,0,0,1,1,73,1,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0" /> <c n="getOWH" v="6" /> <c n="getPA1" v="1" /> <c n="getPA2" v="1" /> <c n="getPA3" v="0" /> <c n="getPA4" v="0" /> <c n="getPA5" v="0" /> <c n="getPA6" v="0" /> <c n="getPA7" v="0" /> <c n="getPA8" v="0" /> <c n="getPB1" v="1" /> <c n="getPB2" v="0" /> <c n="getPB3" v="1" /> <c n="getPB4" v="0" /> <c n="getPB5" v="0" /> <c n="getPB6" v="0" /> <c n="getPB7" v="0" /> <c n="getPB8" v="0" /> <c n="getPF1" v="4000" /> <c n="getPF2" v="3500" /> <c n="getPF3" v="3000" /> <c n="getPF4" v="3500" /> <c n="getPF5" v="3500" /> <c n="getPF6" v="3500" /> <c n="getPF7" v="3500" /> <c n="getPF8" v="3500" /> <c n="getPM1" v="1" /> <c n="getPM2" v="1" /> <c n="getPM3" v="1" /> <c n="getPM4" v="1" /> <c n="getPM5" v="1" /> <c n="getPM6" v="1" /> <c n="getPM7" v="1" /> <c n="getPM8" v="1" /> <c n="getPN1" v="Anwesend" /> <c n="getPN2" v="Abwesend" /> <c n="getPN3" v="" /> <c n="getPN4" v="" /> <c n="getPN5" v="" /> <c n="getPN6" v="" /> <c n="getPN7" v="" /> <c n="getPN8" v="" /> <c n="getPR1" v="0" /> <c n="getPR2" v="0" /> <c n="getPR3" v="24" /> <c n="getPR4" v="0" /> <c n="getPR5" v="0" /> <c n="getPR6" v="0" /> <c n="getPR7" v="0" /> <c n="getPR8" v="0" /> <c n="getPRF" v="1" /> <c n="getPRN" v="2" /> <c n="getPRS" v="41" /> <c n="getPST" v="1" /> <c n="getPT1" v="180" /> <c n="getPT2" v="30" /> <c n="getPT3" v="60" /> <c n="getPT4" v="60" /> <c n="getPT5" v="60" /> <c n="getPT6" v="60" /> <c n="getPT7" v="60" /> <c n="getPT8" v="60" /> <c n="getPV1" v="1000" /> <c n="getPV2" v="30" /> <c n="getPV3" v="300" /> <c n="getPV4" v="300" /> <c n="getPV5" v="300" /> <c n="getPV6" v="300" /> <c n="getPV7" v="300" /> <c n="getPV8" v="300" /> <c n="getPW1" v="0" /> <c n="getPW2" v="0" /> <c n="getPW3" v="1" /> <c n="getPW4" v="0" /> <c n="getPW5" v="0" /> <c n="getPW6" v="0" /> <c n="getPW7" v="0" /> <c n="getPW8" v="0" /> <c n="getRDO" v="90" /> <c n="getRES" v="1255" /> <c n="getRG1" v="0" /> <c n="getRPD" v="3" /> <c n="getRPW" v="0" /> <c n="getRTH" v="15" /> <c n="getRTI" v="00:00" /> <c n="getRTM" v="0" /> <c n="getSCR" v="0" /> <c n="getSIR" v="1" /> <c n="getSLE" v="0" /> <c n="getSLF" v="928" /> <c n="getSLO" v="10" /> <c n="getSLP" v="0" /> <c n="getSLT" v="1216" /> <c n="getSLV" v="76" /> <c n="getSRE" v="0" /> <c n="getSRV" v="" /> <c n="getSS1" v="9" /> <c n="getSTA" v="" /> <c n="getSV1" v="19" /> <c n="getT2" v="1" /> <c n="getTMP" v="0" /> <c n="getTMZ" v="01:00" /> <c n="getTN" v="20" /> <c n="getTOR" v="30" /> <c n="getVLV" v="20" /> <c n="getVS1" v="0" /> <c n="getWHU" v="0" /> <c n="getYHF" v="0,0,0,0,6,1,17,37,1,10,0,5,10,0,0,25,16,1,1,0,9,20,0,0" /> </d> </sc>

**Comment by Ilovegym66** [comment]
er loescht mir hier jedesmal die Ausgabe vom GetAllcommands.. hier ein Screenshot:
![Screenshot 2024-11-08 at 10 37 26](https://github.com/user-attachments/assets/44ad8615-924c-4837-b913-17396e5e9f77)

**Comment by eifel-tech** [comment]
Kannst du mir das XML, was das Gerät sendet, irgendwie als Text zukommen lassen? Einfach nur mit der Fehlermeldung kann ich nichts anfangen, ich muss das lokal debuggen und möchte nicht das Bild abtippen ;-)

**Comment by Ilovegym66** [comment]
ja, ich lad es hier mal als Text hoch.. irgendwie wollte er diesmal hier es nicht anzeigen, wenn ich auf Edit gehe, ist alles da.. speichere ich, wird nichts angezeigt.. deshalb hab ich das Bild gemacht.. 
[syrconnectlog.txt](https://github.com/user-attachments/files/17681222/syrconnectlog.txt)

**Comment by Ilovegym66** [comment]
nochmal von Adapter start an:
[syrconnectlog.txt](https://github.com/user-attachments/files/17681401/syrconnectlog.txt)

**Comment by Ilovegym66** [comment]
schon eine Idee, an was das liegt? Der Adapter setzt kein einziger Wert in die Objekte um, als wuerde er gar keine Daten empfangen..

**Comment by eifel-tech** [comment]
Versuch mal die neuste Version von hier. Es haben sich gefühlt alle Namen der gesendeten Daten geändert, die kennt der Adapter natürlich nicht, die hießen ja vorher anders ;-) Was hast du denn gemacht? Neue Firmware eingespielt vielleicht?

**Comment by Ilovegym66** [comment]
nee, ist noch die gleiche Firmware, V1.9, hat sich auch weder in der App noch am Display was geaendert.
Jetzt kommen die Statistiken, die ich vorher nur in der Webansicht hatte.. Interessant!
Es funktioniert, und, wie gesagt, ich hatte mich nur eingeloggt, ein zusaetzliches altes Profil geloescht, und das standard Profil fuer Anwesend geaendert, mehr hab ich nicht gemacht...

Vielleicht haben die in der Zwischenzeit auch was geaendert, oder durch das aendern werden jetzt mehr Infos geschickt..
Geht, mach doch ein Release :) ich mach hier zu.

**Comment by eifel-tech** [comment]
Release wird gerade gebaut ;-)

**Comment by Ilovegym66** [comment]
du bist ja schneller als der Schall :) Kann man dir irgendwo n Kaffee spendieren? Paypal ?

**Comment by eifel-tech** [comment]
:-D lass mal gut sein, ich sitze eh gerade davor und Release bauen ist ja nur nen Skript starten ;-)
