### ISSUE TITLE
Docker for http server?

### ISSUE THREAD

**Issue by c0ldtech** [eifel-tech/ioBroker.syrconnect#5]
Thanks a lot for your work , if I get this running this is great for me - it's really appreciated!

Not an issue per se, but maybe it would be possible to prepare a simple docker container that takes care of the http server? Or alternatively provide a more detailed howto that outlines what to do to get this running?

I will try setting this up, but I'm afraid I'm a bit out of my depth here.

**Comment by c0ldtech** [comment]
Just to be sure I'm getting this correctly: so it would be fine to setup a redirect that redirects ALL URLs to the adapter without any additional configuration?
So "/WebServices/SyrConnectLimexWebService.asmx/GetBasicCommands" needs to be redirected to "/WebServices/SyrConnectLimexWebService.asmx/GetBasicCommands" on the adapter? Because that should be pretty easy to do. In your howto it sounds like "/WebServices/SyrConnectLimexWebService.asmx/GetBasicCommands" needs to be redirected to "/GetBasicCommands"on the adapter, which would be harder to do since it requires a URL rewrite (as far as I know).

**Comment by c0ldtech** [comment]
Unfortunately, I wasn't able to get it to work for me (Lex10 Connect with current firmware). The management portal of their cloud seems to be reachable under "syrconnect.de", and it shows my Lex10 as online with all the data that it collects. So I guess that's already a sign that it's not working wince it should theoretically push that data to your adapter instead?

**Comment by eifel-tech** [comment]
No, the adapter listens to `/GetBasicCommands` and `/GetAllCommands` as described. But to rewrite the URL is pretty easy. E.g. have a look at my apache-config for rewriting:
> <Location /WebServices/SyrConnectLimexWebService.asmx/>
        RewriteEngine on
	RewriteCond %{REQUEST_URI} ^\/WebServices\/SyrConnectLimexWebService\.asmx\/(.*)$
        RewriteRule ^(.*)$ http://\<<IP of iobroker\>>:8090/%1 [QSA,P,L]
\</Location>
But I can't say how yout have to config other webservers or docker. That will be your turn ;-)

**Comment by eifel-tech** [comment]
Perhaps they changed the URL the Lex 10 communicates with with a newer firmware? My version is 2.8 and I will not update ;-) But you're right, if you get current data in their cloud, you have a problem with the local dns config. Do you get the local webserver IP back by requesting `syrconnect.consoft.de`? That should be the first test with your PC for example.
Additionally the Lex 10 is a little bit bitchy in its network settings. I think it saves a successful dns request for a couple of times, so the config with the local dns would be used if the timeout occurs?! I had a lot of tries myself too :-/ But at the end it worked :-)

**Comment by c0ldtech** [comment]
Where can I see which firmware version my Lex uses?

My local DNS config is fine (regarding syrconnect.consoft.de), I can check locally and everything works as expected - I get redirected to your adapter. So I guess the URL is different. Too bad, I was really looking forward to getting this to work. :(

If I have a lot of free time, I might try to sniff the traffic and see where my Lex actually connects to. Maybe the URL is the only thing that changed.

Thanks for the rewrite rule, I will try to implement this - will need to look for a suitable apache docker first.

Can you confirm that you can actually login to the Syr cloud portal (syrconnect.de) and your Lex appears as offline?

**Comment by c0ldtech** [comment]
Looking at the certificate warning when connecting to syrconnect.consoft.de, they seem to indeed have changed the URL to syrconnect.de, even though the old one still works. I was able to check my firmware version online, and it shows as V6.4 - so I guess I'm out of luck. :(

**Comment by eifel-tech** [comment]
> If I have a lot of free time, I might try to sniff the traffic and see where my Lex actually connects to. Maybe the URL is the only thing that changed.
> 
> Can you confirm that you can actually login to the Syr cloud portal (syrconnect.de) and your Lex appears as offline?

I checked now, my Lex is actually offline at their cloud. Perhaps they support https now, so the Lex will connect to port 443 at the same URL. You can give it a try. But the best way is to sniff your network traffac that's right. 
Or it really doesn't connect to the local dns.

> Looking at the certificate warning when connecting to syrconnect.consoft.de, they seem to indeed have changed the URL to syrconnect.de, even though the old one still works.

That's only a browser problem. The certificate they have is for `syrconnect.de` but not for `consoft.de`. So the browser warns the certificate isn't guilty and he is right ;-) Redirect any browser requests to `https://syrconnect.de` would be the right way and would solve the certificate error. But that's not a note how the Lex communicates with them. You see, per browser you communicate per https (all the time), the Lex per http for years. And if they really only changed the URL, that would be easy for you to configure in your dns ;-) I'm optimistic you get it working.

**Comment by c0ldtech** [comment]
I found another URL - connect.saocal.pl. Unfortunately, my Lex still shows as online in their cloud (with current data), so there probably are other ones as well.

Also, I did not make any progress regarding rewriting the URL using a docker container, I might as well just setup an apache on one of my rpies. Or is there any chance that you could ALSO listen to `/WebServices/SyrConnectLimexWebService.asmx/GetBasicCommands` and `/WebServices/SyrConnectLimexWebService.asmx/GetAllCommands` in addition to the existing listeners? That way the URL would not need to be rewritten, a simple forward would suffice. I know that's effort on your side, but could you check if it's easily possible?

**Comment by eifel-tech** [comment]
I think it's possible. If I have a little bit of time, I'll check your wish :-)

**Comment by c0ldtech** [comment]
Just a heads up: I set up a piHole to get to the bottom of my DNS issues - turns out that my Lex10 is connecting to maintenance.syrconnect.de and syrconnect.de
Now I at least got the redirect working, only issue left for me is either setting something up to rewrite the URLs or hope for you to hve some free time. ;) All in the hope that the URLs are the only things that have been changed and the basic communication stayed the same.

**Comment by eifel-tech** [comment]
Ah, interesting. Hopefully they didn't change basic communication... For rewriting please try version 0.1.1 of the adapter. I updated today ;-) I hope it helps you

**Comment by c0ldtech** [comment]
Great, thank you! I already set the loglevel of the adapter to "debug", can I somehow check if there are even requests arriving on the adapter?

**Comment by eifel-tech** [comment]
If there are requests arriving, the objects (syrconnect.0. etc) will be created ;-) That's the only way to check I think.

Yes, that's the expected behavior, because the server waits for POST requests, not GET

**Comment by c0ldtech** [comment]
Well, I'm giving up for today. When doing curl POST commands to the adapter directly, I at least see error messages in the log.

I don't know how to test the same thing including the redirect: I'm beginning ti suspect that the docker I'm using only works for GET calls, not POST: https://hub.docker.com/r/morbz/docker-web-redirect/

If I find the time during the next few days I'll try to setup a small apache somewhere and try your rewrite rule.

**Comment by eifel-tech** [comment]
The errors occur, because you don't send the expected body. You can test the correct rewriting with Postman (https://www.postman.com/). On monday I can send you the request my Lex sends including correct body if you want ;-) So you can try it with Postman.

**Comment by c0ldtech** [comment]
So unfortunately it seems like the Lex now wants to connect to the cloud using https only. At least that's what my tcpdump tells me if I'm reading it correctly. So unless there is a way to have you adapter listen on a second port using https and using a cutomizeable ssl certificate, I'm all out of luck. :(

**Comment by eifel-tech** [comment]
Well, I'm sorry but there is no need to update the adapter. Even more it's not possible to run an adapter in iobroker that listens on a port lower 8000 because iobroker doesn't run with root rights. 
If they really communicate over https now the webserver has to listen to port 443 and has a certificate installed. It's his job. It can rewrite the requests the same way as I described to the adapter then. I think there is no other way to setup a real webserver (Apache, nginx, ...) by yourself. So I think I'm out now, sorry.
But if you get it running in future or know/found sth about an api to get the lex' data I would be glad to hear you.

**Comment by c0ldtech** [comment]
Another update: success! I created a https listener on the forwarder (in addition to the http listener). Of course that certificate didn't match the (expected) hostname and was not valid, but because of the certificate error, the Lex10 seems to have fallen back to http. Why it did not fall back to http when getting a timeout with https I don't know.
Unfortunately, the most interesting values (for me) are not communicated by the Lex10. The whole statistics section is not being listed, not even the consumption for the current day (I know this is not your fault, you can only show what the Lex is offering).
I could probably try to calculate daily consumption by using the "Restkapazität" value, but...oh well.

Thanks for all your help!

**Comment by Ilovegym66** [comment]
Hi, how you have configured the nginx ?

**Comment by c0ldtech** [comment]
> Hi, how you have configured the nginx ?

I use the nginx reverse proxy manager docker container (jc21/nginx-proxy-manager:latest). There I just set up a forward to the adapter running on iobroker for maintenance.syrconnect.de:

![image](https://github.com/user-attachments/assets/f94467c1-18cd-4fc2-a35f-69a0ecc3e1b7)
