### ISSUE TITLE
Error: Unclosed root tag Line: 52 Column: 29 Char:

### ISSUE THREAD

**Issue by c0ldtech** [eifel-tech/ioBroker.syrconnect#99]
Guten Morgen,

Danke für den Adapter, wir hatten vor einer ganzen Weile schon einmal Austausch hier dazu. :) 

Mit Hilfe eines nginx reverse proxy habe ich am Ende alles zum Laufen bekommen (in meinem Fall musste ich maintenance.syrconnect.de umleiten). Interessanterweise bekomme ich parallel trotzdem noch Daten über das Syr Portal.

Seit circa einer Woche habe ich leider die obige Fehlermeldung im iobroker log und bekomme keine Daten mehr über den Adapter. Ich kann leider nicht sagen, was sich geändert hat. Ich hatte die ganze Zeit noch Version 0.1.1 im Einsatz. Aufgrund des Fehlers habe ich den Adapter auf Version 1.0.0 gehoben, was leider nichts geändert hat.
Ich habe aktuell ungewöhnlich wenig Salz im Behälter, ansonsten fällt mir (bis auf die letzten ioBroker Updates) nichts ein, was anders ist als sonst.
Könntest Du dir das mal anschauen? Kann ich noch etwas an Informationen beisteuern?

Gruß
Hendrik

**Comment by eifel-tech** [comment]
Guten Morgen,

mit Version 1.0 habe ich eigentlich auch nur Dependencies aktualisiert ;-) 
Das wenige Salz würde ich als Ursache vermuten. Hast du das XML, was in deinem Fall vom Gerät verschickt wird? Vielleicht kannst du den Adapter mal im Debug-Modus laufen lassen, ich glaube da wird das ausgegeben. Das klingt mir so, als wäre das XML kaputt, was das Gerät verschickt. 

VG

**Comment by c0ldtech** [comment]
Ja, wird im Debug ausgegeben:

Response: 

`<?xml version="1.0" encoding="utf-8"?><sc version="1.0"><d><c n="getSRN" v=""/><c n="getVER" v=""/><c n="getTYP" v=""/><c n="getCNA" v=""/><c n="getALM" v=""/><c n="getCDE" v=""/><c n="getCS1" v=""/><c n="getCS2" v=""/><c n="getCS3" v=""/><c n="getCYN" v=""/><c n="getCYT" v=""/><c n="getDEN" v=""/><c n="getDGW" v=""/><c n="getDWF" v=""/><c n="getFCO" v=""/><c n="getFIR" v=""/><c n="getFLO" v=""/><c n="getHED" v=""/><c n="getHEM" v=""/><c n="getHEY" v=""/><c n="getHSD" v=""/><c n="getHSM" v=""/><c n="getHSY" v=""/><c n="getIPH" v=""/><c n="getIWH" v=""/><c n="getMAC" v=""/><c n="getMAN" v=""/><c n="getNOT" v=""/><c n="getOWH" v=""/><c n="getPA1" v=""/><c n="getPA2" v=""/><c n="getPA3" v=""/><c n="getPRS" v=""/><c n="getPST" v=""/><c n="getRDO" v=""/><c n="getRES" v=""/><c n="getRG1" v=""/><c n="getRG2" v=""/><c n="getRG3" v=""/><c n="getRPD" v=""/><c n="getRPW" v=""/><c n="getRTH" v=""/><c n="getRTI" v=""/><c n="getRTM" v=""/><c n="getSCR" v=""/><c n="getSRE" v=""/><c n="getSS1" v=""/><c n="getSS2" v=""/><c n="getSS3" v=""/><c n="getSTA" v=""/><c n="getSV1" v=""/><c n="getSV2" v=""/><c n="getSV3" v=""/><c n="getTOR" v=""/><c n="getVAC" v=""/><c n="getVS1" v=""/><c n="getVS2" v=""/><c n="getVS3" v=""/><c n="getWHU" v=""/></d></sc>`

**Comment by c0ldtech** [comment]
Ah, hier nochmal, dann auch mit Werten - aber ja, es sieht so aus als ob das abgeschnitten ist:

`/GetAllCommands: <?xml version="1.0" encoding='iso-8859-2'?> <sc version="1.0"> <d> <c n="getSRN" v="200328829" /> <c n="getVER" v="6.4" /> <c n="getTYP" v="40" /> <c n="getCNA" v="LEX10" /> <c n="getALM" v="" /> <c n="getCDE" v="0102690917.01.033.2.2,0.0010" /> <c n="getCS1" v="47" /> <c n="getCS2" v="0" /> <c n="getCS3" v="0" /> <c n="getCYN" v="0" /> <c n="getCYT" v="00:00" /> <c n="getDEN" v="1" /> <c n="getDGW" v="192.168.15.1" /> <c n="getDWF" v="260" /> <c n="getFCO" v="0" /> <c n="getFIR" v="SE03" /> <c n="getFLO" v="0" /> <c n="getHED" v="0" /> <c n="getHEM" v="0" /> <c n="getHEY" v="0" /> <c n="getHSD" v="0" /> <c n="getHSM" v="0" /> <c n="getHSY" v="0" /> <c n="getIPH" v="" /> <c n="getIWH" v="25" /> <c n="getMAC" v="0c:73:eb:50:7f:b6" /> <c n="getMAN" v="Syr" /> <c n="getNOT" v="" /> <c n="getOWH" v="7" /> <c n="getPA1" v="0" /> <c n="getPA2" v="0" /> <c n="getPA3" v="0" /> <c n="getPRS" v="50" /> <c n="getPST" v="1" /> <c n="getRDO" v="80" /> <c n="getRES" v="516" /> <c n="getRG1" v="0" /> <c n="getRG2" v="0" /> <c n="getRG3" v="0" /> <c n="getRPD" v="0" /> <c n="getRPW" v="0" /> <c n="getRTH" v="2" /> <c n="getRTI" v="00:00" /> <c n="getRTM" v="0" /> <c n="getSCR" v="0" /> <c n="getSRE" v="1" /> <c n="getSS1" v="100" /> <c n="getSS2" v="0" /> <c n="getSS3" v="0" /> <c n="getSTA" v="Salt amount`

**Comment by eifel-tech** [comment]
Das unvollständige kommt vom Gerät. Deswegen kann der Adapter das XML nicht parsen und schmeißt den Fehler. Das lässt sich auch im Adapter nicht wirklich reparieren außer eine (aussagekräftigere) Fehlermeldung ins Log zu schreiben. Parsen geht ja dann immer noch nicht und Werte bekommst du dann natürlich auch nicht.

**Comment by c0ldtech** [comment]
Wenn das schon so fehlerhaft ankommt, dann wäre es wohl wirklich nicht sinnvoll, da irgendwie drum herum zu basteln. Danke dir!
